service: sunmap-endpoints

plugins:
  - serverless-python-requirements
  - serverless-offline
  
package:
  exclude:
    - node_modules/**
    - .env

custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-2
  profile: serverless-deployments

functions:
  list:
    handler: handler.api
    events:
      - http:
          path: /api/v1/{lat}/{lng}
          method: get
          cors: true

