org: kipxx
app: sunmap-endpoints-app
service: sunmap-endpoints

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-domain-manager

custom:
  pythonRequirements:
    dockerizePip: non-linux
  customDomain:
    domainName: sunrise.fifthcontinent.io
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

package:
  exclude:
    - node_modules/**
    - .env

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-2
  profile: serverless-deployments


functions:
  sunrise:
    handler: handler.api
    events:
      - http:
          path: /api/v1/{lat}/{lng}
          method: get
          cors: true
  root:
    handler: handler.root
    events:
      - http:
          path: /
          method: get
          cors: true
  info:
    handler: handler.info
    events:
      - http:
          path: /api/v1
          method: get
          cors: true


