openapi: 3.0.0
info:
  title: Sunrise API
  description: Retrieve sunset and sunrise times for any location and date
  version: 0.1.9
servers:
  - url: "https://sunrise.fifthcontinent.io"
paths:
  /api/v1/{latitude}/{longitude}:
    get:
      summary: Returns the sunrise and sunset for a location, by default for the current day but optionally for any date range defined by fromDate and toDate
      parameters:
        - name: "latitude"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "longitude"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "fromDate"
          in: "query"
          required: false
          schema:
            type: "string"
        - name: "toDate"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        '200':    # status code
          description: A JSON object with timezone information and a list of objects with sunrise and sunset for requested days
          content:
            application/json:
              schema:
                type: object
                properties:
                  timezone:
                    type: string
                    example: "Europe/London"
                  longitude:
                    type: number
                    example: 121.611908
                  latitude:
                    type: number
                    example: 23.563987
                  days:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          example: "2021-11-25"
                        times:
                          type: object
                          properties:
                            sunrise:
                              type: string
                              example: "2021-11-25T07:34:03+00:00"
                            sunset:
                              type: string
                              example: "2021-11-25T07:34:03+00:00"
                   